name: Gatsby Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build Gatsby site
        run: yarn build

      - name: Deploy to publish branch
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -B publish
          git add -f public/*
          git commit -m "Deploy Gatsby build to publish branch"
          cat ${GH_TOKEN}
          git push https://x-access-token:${GH_TOKEN}@github.com/GGos3/blog.git publish --force